services:
  db:
    image: mysql:5.6.43
    ports:
      - 3307:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE_FILE=/run/secrets/db.txt
      - MYSQL_USER_FILE=/run/secrets/db.txt
      - MYSQL_PASSWORD_FILE=/run/secrets/pwd.txt
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d
      - ./secrets:/run/secrets/

  apache:
    build: .
    ports:
      - 80:80
    environment:
      DB_DOCKER_HOST: db
      DB_DOCKER_SCHEMA: http
    volumes:
      - ../:/var/www/app/
    depends_on:
      - db
