<?

$PAGES['default'] = "default";
$PAGES['section'] = "section";
$PAGES['partner'] = "partner";
$PAGES['event'] = "event";
$PAGES['department'] = "department";
$PAGES['daily'] = "daily";
$PAGES['service'] = "service";
$PAGES['review'] = "review";
$PAGES['user'] = "user";
$PAGES['clinic'] = "clinic";
$PAGES['doctor'] = "doctor";
$PAGES['price'] = "price";
$PAGES['stock'] = "stock";
$PAGES['article'] = "article";
$PAGES['hot'] = "hot";
$PAGES['error404'] = "error404";
$PAGES['sitemap'] = "sitemap";
$PAGES['test'] = "test";
$PAGES['release'] = "release";
$PAGES['galfilter'] = "galfilter";
$PAGES['galvmenu'] = "galvmenu";
$PAGES['catmenu'] = "catmenu";
$PAGES['search'] = "search";

define ("MOD_DEFAULT",0);
define ("MOD_MENU",1);
define ("MOD_SECTION",2);
define ("MOD_PARTNER",4);
define ("MOD_EVENT",6);
define ("MOD_PHOTO",7);
define ("MOD_CLINIC",8);
define ("MOD_DEPARTMENT",9);
define ("MOD_DAILY",10);
define ("MOD_DOCTOR",11);
define ("MOD_SERVICE",12);
define ("MOD_ARTICLE",13);
define ("MOD_REVIEW",14);
define ("MOD_PRICE",15);
define ("MOD_STOCK",16);
define ("MOD_HOT",17);
define ("MOD_USER",18);
define ("MOD_ERROR404",19);
define ("MOD_SITEMAP",20);
define ("MOD_TEST",21);
define ("MOD_RELEASE",22);
define ("MOD_GALFILTER",23);
define ("MOD_GALVMENU",24);
define ("MOD_CATMENU",25);
define ("MOD_SEARCH",26);

$MODULES[MOD_DEFAULT] = array("default","cModDefault");
$MODULES[MOD_MENU] = array("menu","cModMenu");
$MODULES[MOD_SECTION] = array("section","cModSection");
$MODULES[MOD_PARTNER] = array("partner","cModPartner");
$MODULES[MOD_EVENT] = array("event","cModEvent");
$MODULES[MOD_DEPARTMENT] = array("department","cModDepartment");
$MODULES[MOD_DAILY] = array("daily","cModDaily");
$MODULES[MOD_SERVICE] = array("service","cModService");
$MODULES[MOD_REVIEW] = array("review","cModReview");
$MODULES[MOD_USER] = array("user","cModUser");
$MODULES[MOD_CLINIC] = array("clinic","cModClinic");
$MODULES[MOD_DOCTOR] = array("doctor","cModDoctor");
$MODULES[MOD_PRICE] = array("price","cModPrice");
$MODULES[MOD_STOCK] = array("stock","cModStock");
$MODULES[MOD_ARTICLE] = array("article","cModArticle");
$MODULES[MOD_HOT] = array("hot","cModHot");
$MODULES[MOD_ERROR404] = array("error404","cModError404");
$MODULES[MOD_SITEMAP] = array("sitemap","cModSitemap");
$MODULES[MOD_TEST] = array("test","cModTest");
$MODULES[MOD_RELEASE] = array("release","cModRelease");
$MODULES[MOD_GALFILTER] = array("galfilter","cModGalfilter");
$MODULES[MOD_GALVMENU] = array("galvmenu","cModGalvmenu");
$MODULES[MOD_CATMENU] = array("catmenu","cModCatmenu");
$MODULES[MOD_SEARCH] = array("search","cModSearch");

?>