<?

$PAGES['default'] = "default";
$PAGES['main'] = "main";
$PAGES['tree'] = "tree";
$PAGES['settings'] = "settings";
$PAGES['dailys'] = "dailys";
$PAGES['events'] = "events";
$PAGES['maintexts'] = "maintexts";
$PAGES['partners'] = "partners";
$PAGES['services'] = "services";
$PAGES['stocks'] = "stocks";
$PAGES['videos'] = "videos";
$PAGES['photos'] = "photos";
$PAGES['reviews'] = "reviews";
$PAGES['sliders'] = "sliders";
$PAGES['users'] = "users";
$PAGES['medias'] = "medias";
$PAGES['articles'] = "articles";
$PAGES['releases'] = "releases";
$PAGES['offers'] = "offers";
$PAGES['departments'] = "departments";
$PAGES['clinics'] = "clinics";
$PAGES['specializations'] = "specializations";
$PAGES['doctors'] = "doctors";
$PAGES['comments'] = "comments";
$PAGES['advantages'] = "advantages";
$PAGES['gallerys'] = "gallerys";

define ("MOD_DEFAULT",0);
define ("MOD_MAIN",1);
define ("MOD_TREE",2);
define ("MOD_MENU",3);
define ("MOD_SETTINGS",4);
define ("MOD_MAINTEXTS",5);
define ("MOD_DAILYS",6);
define ("MOD_EVENTS",7);
define ("MOD_PHOTOS",8);
define ("MOD_PARTNERS",9);
define ("MOD_SERVICES",10);
define ("MOD_STOCKS",11);
define ("MOD_VIDEOS",12);
define ("MOD_REVIEWS",13);
define ("MOD_SLIDERS",14);
define ("MOD_USERS",15);
define ("MOD_MEDIAS",16);
define ("MOD_ARTICLES",17);
define ("MOD_RELEASES",18);
define ("MOD_OFFERS",19);
define ("MOD_DEPARTMENTS",20);
define ("MOD_CLINICS",21);
define ("MOD_SPECIALIZATIONS",22);
define ("MOD_DOCTORS",23);
define ("MOD_COMMENTS",24);
define ("MOD_ADVANTAGES",25);
define ("MOD_GALLERYS",26);

$MODULES[MOD_DEFAULT] = array("default","cModDefault");
$MODULES[MOD_MAIN] = array("main","cModMain");
$MODULES[MOD_MENU] = array("menu","cModMenu");
$MODULES[MOD_TREE] = array("tree","cModTree");
$MODULES[MOD_SETTINGS] = array("settings","cModSettings");
$MODULES[MOD_DAILYS] = array("dailys","cModDailys");
$MODULES[MOD_EVENTS] = array("events","cModEvents");
$MODULES[MOD_MAINTEXTS] = array("maintexts","cModMaintexts");
$MODULES[MOD_PARTNERS] = array("partners","cModPartners");
$MODULES[MOD_SERVICES] = array("services","cModServices");
$MODULES[MOD_STOCKS] = array("stocks","cModStocks");
$MODULES[MOD_VIDEOS] = array("videos","cModVideos");
$MODULES[MOD_REVIEWS] = array("reviews","cModReviews");
$MODULES[MOD_SLIDERS] = array("sliders","cModSliders");
$MODULES[MOD_USERS] = array("users","cModUsers");
$MODULES[MOD_PHOTOS] = array("photos","cModPhotos");
$MODULES[MOD_MEDIAS] = array("medias","cModMedias");
$MODULES[MOD_RELEASES] = array("releases","cModReleases");
$MODULES[MOD_ARTICLES] = array("articles","cModArticles");
$MODULES[MOD_OFFERS] = array("offers","cModOffers");
$MODULES[MOD_DEPARTMENTS] = array("departments","cModDepartments");
$MODULES[MOD_CLINICS] = array("clinics","cModClinics");
$MODULES[MOD_SPECIALIZATIONS] = array("specializations","cModSpecializations");
$MODULES[MOD_DOCTORS] = array("doctors","cModDoctors");
$MODULES[MOD_COMMENTS] = array("comments","cModComments");
$MODULES[MOD_ADVANTAGES] = array("advantages","cModAdvantages");
$MODULES[MOD_GALLERYS] = array("gallerys","cModGallerys");

?>